### ISSUE TITLE
 => ERROR [frontend build-node-stage  5/13] RUN ["npm", "install"] 

### ISSUE THREAD

**Issue by Tchagoue** [lias-laboratory/rql#1]
Hello,
I encountered the following error while running `_**docker compose build**_`. Could you please tell me how to solve it? It is because I am using a Mac?
Thank's.

 > [frontend build-node-stage  5/13] RUN ["npm", "install"]:
6.402 npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
6.410 npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
6.412 npm WARN deprecated domelementtype@1.3.0: update to domelementtype@1.3.1
...
g/releases.json instead
10.18 npm WARN deprecated core-js@2.5.3: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
11.63 npm notice 
11.63 npm notice New patch version of npm available! 10.5.0 -> 10.5.2
11.63 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.2>
11.63 npm notice Run `npm install -g npm@10.5.2` to update!
11.63 npm notice 
11.63 npm ERR! code 1
11.63 npm ERR! path /work/node_modules/chromedriver
11.63 npm ERR! command failed
11.63 npm ERR! command sh -c node install.js
11.63 npm ERR! Only Linux 64 bits supported.
11.63 
11.63 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-25T07_13_23_740Z-debug-0.log
------
failed to solve: process "npm install" did not complete successfully: exit code: 1

**Comment by mickaelbaron** [comment]
Dear @Tchagoue,

Thank you for your interest in RQL.

According to your logs, build is not possible on ARM architecture. We have not yet tested on ARM architectures

Sorry we can't satisfy your request. 

Mickael

**Comment by Tchagoue** [comment]
Thanks, I tried it on the Dell,
and encountered no issues.

**Comment by mickaelbaron** [comment]
Cool

We are going to notify on the README.md file that the compilation is only for x86 architecture ... for this moment

However, I keep open this issue

Mickael

**Comment by mickaelbaron** [comment]
Dear @Tchagoue,

I have just investigated compilation for ARM. With Docker Desktop on ARM Mac (M1, M2, and M3), it is possible to compile by selecting the architecture. I quickly tested it on a colleague's Mac, and it worked (I am still on x86 architecture). I will conduct a more comprehensive test and get back to you.

Best

**Comment by bchardin** [comment]
The proposed solution is to use an emulated environment for the front-end container of RQL.  
This seems acceptable as most of RQL execution time is on the back-end.

If anyone wants to update the front-end implementation to support other architectures natively, it would be most welcome.
